name: Sales Bot Execution

on:
  workflow_dispatch:      # Isse GitHub par "Run workflow" ka button mil jayega
  schedule:
    - cron: '30 23 * * *' # Roz Subah 05:00 AM IST (11:30 PM UTC) par apne aap chalega

jobs:
  run-sales:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Yeh step check karega ki file sahi jagah par hai ya nahi
      - name: List Files (Debug)
        run: ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install simple-salesforce selenium webdriver-manager

      - name: Run Script
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_TOKEN: ${{ secrets.SF_TOKEN }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python sales_bot.py
